steps:
  # Dockerコンテナのビルド
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/bgr4-front:latest"
      - "."

  # GCRへのイメージのプッシュ
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/bgr4-front:latest"

  # Cloud Runへのデプロイ
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "bgr4-front"
      - "--image"
      - "gcr.io/$PROJECT_ID/bgr4-front:latest"
      - "--region"
      - "asia-northeast1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "3000"
      - "--memory"
      - "1024Mi"
      - "--cpu"
      - "1"
      - "--min-instances"
      - "1"
      - "--max-instances"
      - "2"
      - "--set-env-vars"
      - "NODE_ENV=production,NEXT_PUBLIC_API_URL=https://bgr4-api-349403738734.asia-northeast1.run.app,NEXT_PUBLIC_BROWSER_API_URL=https://bgr4-api-349403738734.asia-northeast1.run.app,NEXT_PUBLIC_USE_MOCK_DATA=false,NEXT_PUBLIC_GOOGLE_CLIENT_ID=853311366559-go3q4p3ogloheehm7hhgl0ab8qcgbolt.apps.googleusercontent.com,NEXT_PUBLIC_TWITTER_CLIENT_ID=ZU9URGY0aVFibWVyOC1wVk5CMXQ6MTpjaQ,NEXT_PUBLIC_API_DIRECT=true"

images:
  - "gcr.io/$PROJECT_ID/bgr4-front:latest"

timeout: "1800s"
