steps:
  # Dockerコンテナのビルド
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/bgr5-api-games:latest"
      - "."

  # GCRへのイメージのプッシュ
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/bgr5-api-games:latest"

  # Cloud Runへのデプロイ
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "bgr5-api-games"
      - "--image"
      - "gcr.io/$PROJECT_ID/bgr5-api-games:latest"
      - "--region"
      - "asia-northeast1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"
      - "--memory"
      - "512Mi"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "2"
      - "--set-env-vars"
      - "RAILS_ENV=production,RAILS_SERVE_STATIC_FILES=true,DATABASE_URL=postgresql://bgr5_user:postgres@35.200.15.8:5432/bgr5_production,DATABASE_HOST=35.200.15.8,DATABASE_PORT=5432,POSTGRES_USER=bgr5_user,POSTGRES_PASSWORD=postgres,FRONTEND_URL=https://bgr5-front-y2i5irl3rq-an.a.run.app,CORS_ORIGINS=https://bgr5-front-y2i5irl3rq-an.a.run.app"
      # 注意: 以下の環境変数はCloud Run Consoleで直接設定してください
      # GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, TWITTER_CLIENT_ID, TWITTER_CLIENT_SECRET

images:
  - "gcr.io/$PROJECT_ID/bgr5-api-games:latest"

timeout: "1800s"
