steps:
  # Gemsイメージを構築
  - id: "build-gems"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--tag=gcr.io/$PROJECT_ID/bgr5-api-gems:latest"
      - "--target=gems"
      - "."

  # 最終イメージを構築
  - id: "build-app"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--tag=gcr.io/$PROJECT_ID/bgr5-api:latest"
      - "."

  # アプリケーションイメージをGCRにプッシュ
  - id: "push-app"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/bgr5-api:latest"]

  # Gemsイメージをプッシュ
  - id: "push-gems"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/bgr5-api-gems:latest"]

  # Cloud Runにデプロイ
  - id: "deploy"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "bgr5-api"
      - "--image=gcr.io/$PROJECT_ID/bgr5-api:latest"
      - "--region=asia-northeast1"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--memory=1Gi"
      - "--cpu=1"
      - "--min-instances=0"
      - "--max-instances=1"
      - "--set-env-vars=RAILS_ENV=production"
      - "--set-env-vars=DATABASE_URL=postgres://postgres:postgres@35.200.15.8:5432/bgr5_production"
      - "--set-env-vars=SECRET_KEY_BASE=a8b2349882935c4cfcfa0d68930f110b3df512be382d55349ed6d66b766e93d6450564825f8bfb26a4b445b0a5ed18ecacf4ccb4aa9b70f0c0a815251b03c5a7"
      - "--set-env-vars=RAILS_LOG_TO_STDOUT=true"
      - "--set-env-vars=RAILS_SERVE_STATIC_FILES=true"
      - "--set-env-vars=MALLOC_ARENA_MAX=2"
      - "--set-env-vars=WEB_CONCURRENCY=1"
      - "--set-env-vars=RAILS_MAX_THREADS=5"

# イメージ一覧
images:
  - "gcr.io/$PROJECT_ID/bgr5-api:latest"
  - "gcr.io/$PROJECT_ID/bgr5-api-gems:latest"

timeout: "1800s"
