source "https://rubygems.org"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.1.2"
# Use postgresql as the database for Active Record
gem "pg", "~> 1.5.3"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"
# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# PostgreSQL接続プールの最適化
gem "connection_pool", "~> 2.4"

# Use Active Model has_secure_password
gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Use the database-backed adapters for Rails.cache, Active Job, and Action Cable
gem "redis", "~> 4.0"
# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Deploy this application anywhere as a Docker container [https://kamal-deploy.org]
gem "kamal", require: false

# Add HTTP asset caching/compression and X-Sendfile acceleration to Puma [https://github.com/basecamp/thruster/]
gem "thruster", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
gem "rack-cors"

# Use JWT for token-based authentication
gem "jwt"

# HTTP通信用のgem
gem 'http'
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem 'omniauth-twitter2'  # Twitter OAuth2用のgemを追加
gem 'omniauth-rails_csrf_protection'
gem 'devise'
gem 'devise_token_auth'

# Internationalization
gem 'rails-i18n', '~> 7.0.0'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem "brakeman", require: false

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false
  
  # メールのプレビュー用
  gem 'letter_opener'
  gem 'letter_opener_web'

  # 環境変数の管理
  gem 'dotenv-rails'
end

group :production do
  # 本番環境向けロギング
  gem 'lograge'
  
  # エラートラッキング
  gem 'sentry-ruby'
  gem 'sentry-rails'
end

gem "google-cloud-translate", "~> 3.7"

gem "httparty", "~> 0.22.0"

# JSONシリアライズ用のgem
gem "active_model_serializers", "~> 0.10.13"
